import type { CommandSpec, ToolDefinition } from './types';

const npmInstall = (name: string, label: string): CommandSpec => ({
  executable: 'npm',
  args: ['install', '--global', name],
  description: `Instalar ${label} globalmente com npm`,
  permission: 'install-dependencies',
  risk: 'write',
  timeoutMs: 120_000,
});
const brewInstall = (formula: string, label: string): CommandSpec => ({
  executable: 'brew',
  args: ['install', formula],
  description: `Instalar ${label} com Homebrew`,
  permission: 'install-dependencies',
  risk: 'write',
  timeoutMs: 180_000,
});

export const toolCatalog: readonly ToolDefinition[] = [
  {
    id: 'git',
    name: 'Git',
    command: 'git',
    category: 'core',
    documentationUrl: 'https://git-scm.com/downloads',
    versionArgs: ['--version'],
    install: brewInstall('git', 'Git'),
  },
  {
    id: 'github',
    name: 'GitHub CLI',
    command: 'gh',
    category: 'core',
    documentationUrl: 'https://cli.github.com/manual/',
    versionArgs: ['--version'],
    install: brewInstall('gh', 'GitHub CLI'),
  },
  {
    id: 'node',
    name: 'Node.js',
    command: 'node',
    category: 'runtime',
    documentationUrl: 'https://nodejs.org/en/download',
    versionArgs: ['--version'],
    install: brewInstall('node', 'Node.js'),
  },
  {
    id: 'npm',
    name: 'npm',
    command: 'npm',
    category: 'package-manager',
    documentationUrl: 'https://docs.npmjs.com/downloading-and-installing-node-js-and-npm',
    versionArgs: ['--version'],
  },
  {
    id: 'pnpm',
    name: 'pnpm',
    command: 'pnpm',
    category: 'package-manager',
    documentationUrl: 'https://pnpm.io/installation',
    versionArgs: ['--version'],
    install: npmInstall('pnpm', 'pnpm'),
  },
  {
    id: 'yarn',
    name: 'Yarn',
    command: 'yarn',
    category: 'package-manager',
    documentationUrl: 'https://yarnpkg.com/getting-started/install',
    versionArgs: ['--version'],
    install: npmInstall('yarn', 'Yarn'),
  },
  {
    id: 'bun',
    name: 'Bun',
    command: 'bun',
    category: 'package-manager',
    documentationUrl: 'https://bun.sh/docs/installation',
    versionArgs: ['--version'],
    install: brewInstall('oven-sh/bun/bun', 'Bun'),
  },
  {
    id: 'firebase',
    name: 'Firebase CLI',
    command: 'firebase',
    category: 'deploy',
    documentationUrl: 'https://firebase.google.com/docs/cli',
    versionArgs: ['--version'],
    install: npmInstall('firebase-tools', 'Firebase CLI'),
  },
  {
    id: 'vercel',
    name: 'Vercel CLI',
    command: 'vercel',
    category: 'deploy',
    documentationUrl: 'https://vercel.com/docs/cli',
    versionArgs: ['--version'],
    install: npmInstall('vercel@latest', 'Vercel CLI'),
  },
  {
    id: 'supabase',
    name: 'Supabase CLI',
    command: 'supabase',
    category: 'deploy',
    documentationUrl: 'https://supabase.com/docs/guides/local-development/cli/getting-started',
    versionArgs: ['--version'],
    install: brewInstall('supabase/tap/supabase', 'Supabase CLI'),
  },
  {
    id: 'docker',
    name: 'Docker',
    command: 'docker',
    category: 'runtime',
    documentationUrl: 'https://docs.docker.com/get-docker/',
    versionArgs: ['--version'],
  },
  {
    id: 'python',
    name: 'Python',
    command: 'python3',
    alternateCommands: ['python'],
    category: 'runtime',
    documentationUrl: 'https://www.python.org/downloads/',
    versionArgs: ['--version'],
    install: brewInstall('python', 'Python'),
  },
  {
    id: 'claude',
    name: 'Claude Code',
    command: 'claude',
    category: 'agent',
    documentationUrl: 'https://docs.anthropic.com/en/docs/claude-code/getting-started',
    versionArgs: ['--version'],
    install: npmInstall('@anthropic-ai/claude-code', 'Claude Code'),
  },
  {
    id: 'codex',
    name: 'Codex CLI',
    command: 'codex',
    category: 'agent',
    documentationUrl: 'https://developers.openai.com/codex/cli/',
    versionArgs: ['--version'],
    install: npmInstall('@openai/codex', 'Codex CLI'),
  },
  {
    id: 'gemini',
    name: 'Gemini CLI',
    command: 'gemini',
    category: 'agent',
    documentationUrl: 'https://github.com/google-gemini/gemini-cli',
    versionArgs: ['--version'],
    install: npmInstall('@google/gemini-cli', 'Gemini CLI'),
  },
  {
    id: 'aider',
    name: 'Aider',
    command: 'aider',
    category: 'agent',
    documentationUrl: 'https://aider.chat/docs/install.html',
    versionArgs: ['--version'],
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    command: 'opencode',
    category: 'agent',
    documentationUrl: 'https://opencode.ai/docs/',
    versionArgs: ['--version'],
  },
  {
    id: 'ollama',
    name: 'Ollama',
    command: 'ollama',
    category: 'agent',
    documentationUrl: 'https://ollama.com/download',
    versionArgs: ['--version'],
    install: brewInstall('ollama', 'Ollama'),
  },
  {
    id: 'lm-studio',
    name: 'LM Studio',
    command: 'lms',
    category: 'agent',
    documentationUrl: 'https://lmstudio.ai/docs/cli',
    versionArgs: ['--version'],
  },
];

export const getToolDefinition = (id: string): ToolDefinition | undefined =>
  toolCatalog.find((tool) => tool.id === id);
